baseURL = "https://sammachin.com/"
languageCode = "en-us"
title = "Sam Machin"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true


[params]
title = "Sam Machin"
author = "Sam Machin"
description = "Product Manager, Hacker, Geek"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["posts", "projects"]


## Social links

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/sammachin/"

[[params.socialIcons]]
icon = "fa-twitter"
title = "twitter"
url = "https://twitter.com/sammachin"

[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/sammachin"


## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"
 

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
 
  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"
 
  [[menu.main]]
  name = "Projects"
  weight = 200
  identifier = "projects"
  url = "/projects/"